distributor:
    routes:
        eb993a48-87f5-4047-b4e9-992169e9e541:
            uuid: eb993a48-87f5-4047-b4e9-992169e9e541
            weight: 10000
            value:
                type: pardot
                pass: ''
                config:
                    pardot:
                        enabled: true
                        async: inherit
                        disableStorage: inherit
                        enableDataProviders:
                            type: all
                            config:
                                all: {  }
                        gate:
                            type: 'true'
                            config:
                                'true': {  }
                        data:
                            fieldMap:
                                fields:
                                    6aab3db3-de07-4c93-bfd6-36888b7d11fb:
                                        uuid: 6aab3db3-de07-4c93-bfd6-36888b7d11fb
                                        weight: 10000
                                        key: source
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: source
                                            modifiers: {  }
                                    00754c90-7f10-4141-baef-067669bc13ca:
                                        uuid: 00754c90-7f10-4141-baef-067669bc13ca
                                        weight: 10100
                                        key: salutation
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: salutation
                                            modifiers: {  }
                                    635adce2-22d6-47b9-b022-88ed32e92104:
                                        uuid: 635adce2-22d6-47b9-b022-88ed32e92104
                                        weight: 10200
                                        key: first_name
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: first_name
                                            modifiers: {  }
                                    ac446a86-8a31-4818-8803-fa27155c2e88:
                                        uuid: ac446a86-8a31-4818-8803-fa27155c2e88
                                        weight: 10300
                                        key: last_name
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: last_name
                                            modifiers: {  }
                                    cb00055c-069a-4fe9-9d24-f5bb7ab5b8cb:
                                        uuid: cb00055c-069a-4fe9-9d24-f5bb7ab5b8cb
                                        weight: 10400
                                        key: email
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: email
                                            modifiers: {  }
                                    bf3ad0f2-57c6-4956-8a89-36d0ad5e9ed6:
                                        uuid: bf3ad0f2-57c6-4956-8a89-36d0ad5e9ed6
                                        weight: 10500
                                        key: phone
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: phone
                                            modifiers: {  }
                                    7264f466-6450-49da-9660-64aa147b92e8:
                                        uuid: 7264f466-6450-49da-9660-64aa147b92e8
                                        weight: 10600
                                        key: fax
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: fax
                                            modifiers: {  }
                                    b7491b4a-7a76-43f2-a649-3fb763f08c6e:
                                        uuid: b7491b4a-7a76-43f2-a649-3fb763f08c6e
                                        weight: 10700
                                        key: company
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: company
                                            modifiers: {  }
                                    3cbd908e-8c65-4f15-b6e0-7e9fc18c788b:
                                        uuid: 3cbd908e-8c65-4f15-b6e0-7e9fc18c788b
                                        weight: 10800
                                        key: industry
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: industry
                                            modifiers: {  }
                                    e6ab688a-7892-40e9-bf0d-52bc1df1d146:
                                        uuid: e6ab688a-7892-40e9-bf0d-52bc1df1d146
                                        weight: 10900
                                        key: department
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: department
                                            modifiers: {  }
                                    2eb55c10-eb09-47cc-a04b-ab76736af0ee:
                                        uuid: 2eb55c10-eb09-47cc-a04b-ab76736af0ee
                                        weight: 11000
                                        key: job_title
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: job_title
                                            modifiers: {  }
                                    835744ef-b710-4959-b8e9-aa743b954f2c:
                                        uuid: 835744ef-b710-4959-b8e9-aa743b954f2c
                                        weight: 11100
                                        key: website
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: website
                                            modifiers: {  }
                                    f9dc9bdb-8986-4fef-85d1-828f0b9fa805:
                                        uuid: f9dc9bdb-8986-4fef-85d1-828f0b9fa805
                                        weight: 11200
                                        key: annual_revenue
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: annual_revenue
                                            modifiers: {  }
                                    59a01705-3c54-4f35-8095-8455a82cc148:
                                        uuid: 59a01705-3c54-4f35-8095-8455a82cc148
                                        weight: 11300
                                        key: years_in_business
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: years_in_business
                                            modifiers: {  }
                                    6d158dbb-30a4-4e6a-a2c5-004f780294b9:
                                        uuid: 6d158dbb-30a4-4e6a-a2c5-004f780294b9
                                        weight: 11400
                                        key: employees
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: employees
                                            modifiers: {  }
                                    9534f276-ed79-48a4-9b9e-26f96295aec2:
                                        uuid: 9534f276-ed79-48a4-9b9e-26f96295aec2
                                        weight: 11500
                                        key: address_one
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: address_one
                                            modifiers: {  }
                                    e5f49333-eecf-4cfe-9b81-99270ae31631:
                                        uuid: e5f49333-eecf-4cfe-9b81-99270ae31631
                                        weight: 11600
                                        key: address_two
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: address_two
                                            modifiers: {  }
                                    dde86d6c-e423-4106-aca0-2ded9603625c:
                                        uuid: dde86d6c-e423-4106-aca0-2ded9603625c
                                        weight: 11700
                                        key: zip
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: zip
                                            modifiers: {  }
                                    7a7be38a-593d-40be-b4b6-fbc10e1b81d9:
                                        uuid: 7a7be38a-593d-40be-b4b6-fbc10e1b81d9
                                        weight: 11800
                                        key: city
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: city
                                            modifiers: {  }
                                    d789d9b3-18be-4ee5-86f2-f5626bd9311d:
                                        uuid: d789d9b3-18be-4ee5-86f2-f5626bd9311d
                                        weight: 11900
                                        key: state
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: state
                                            modifiers: {  }
                                    036f5b86-d740-49bc-9da2-cfd7d54c4374:
                                        uuid: 036f5b86-d740-49bc-9da2-cfd7d54c4374
                                        weight: 12000
                                        key: country
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: country
                                            modifiers: {  }
                                    a148358b-d5e9-4eef-9758-68b457bd6a0e:
                                        uuid: a148358b-d5e9-4eef-9758-68b457bd6a0e
                                        weight: 12100
                                        key: territory
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: territory
                                            modifiers: {  }
                                    441514ba-7601-4a77-826f-b5bc5c6d74d6:
                                        uuid: 441514ba-7601-4a77-826f-b5bc5c6d74d6
                                        weight: 12200
                                        key: is_do_not_call
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: is_do_not_call
                                            modifiers: {  }
                                    2dc62853-c3a1-42e6-b0ab-d853e73d8ae5:
                                        uuid: 2dc62853-c3a1-42e6-b0ab-d853e73d8ae5
                                        weight: 12300
                                        key: is_do_not_email
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: is_do_not_email
                                            modifiers: {  }
                                    624580cc-c07f-47b1-a7df-27af230af99d:
                                        uuid: 624580cc-c07f-47b1-a7df-27af230af99d
                                        weight: 12400
                                        key: opted_out
                                        value:
                                            data:
                                                type: field
                                                config:
                                                    field:
                                                        fieldName: opted_out
                                            modifiers: {  }
                                    81d81f98-886e-4105-9b62-77ba47ed4312:
                                        uuid: 81d81f98-886e-4105-9b62-77ba47ed4312
                                        weight: 12500
                                        key: comments
                                        value:
                                            data:
                                                type: fieldCollector
                                                config:
                                                    fieldCollector:
                                                        unprocessedOnly: true
                                                        ignoreIfEmpty: true
                                                        exclude: ''
                                                        include: ''
                                                        template: '{key}\s=\s{value}\n'
                                            modifiers: {  }
                            passthroughFields:
                                enabled: false
                            ignoreEmptyFields:
                                enabled: true
                            excludeFields:
                                fields: {  }
                            prefix:
                                prefix: ''
                                action: add
                        url: ''
                        cookies:
                            1545dffa-c23e-4fbd-9910-715c0a9b9b7c:
                                uuid: 1545dffa-c23e-4fbd-9910-715c0a9b9b7c
                                weight: 10000
                                key: 'visitor_id[0-9]+(-hash)?'
                                value: '{value}'
                        headers:
                            994d58f9-2c5f-4fe1-b2e0-8e6ee30198f4:
                                uuid: 994d58f9-2c5f-4fe1-b2e0-8e6ee30198f4
                                weight: 10000
                                key: User-Agent
                                value: '{value}'
metaData:
    name: Pardot Route
    version:
        core: 1.0.0
        distributor-core: 1.0.0
        distributor-pardot: 1.0.0
        distributor-request: 1.0.0
    includes: {  }
